SUGAR: SPEED
HONEY_BLOCK: SLOWNESS
RABBIT_FOOT: JUMP_BOOST
GLISTERING_MELON_SLICE: INSTANT_HEALTH
SPIDER_EYE: POISON
DRIPSTONE_BLOCK: INSTANT_DAMAGE
PUFFERFISH: WATER_BREATHING
MAGMA_CREAM: FIRE_RESISTANCE
GOLDEN_CARROT: NIGHT_VISION
GLASS: INVISIBILITY
BLAZE_POWDER: STRENGTH
FERMENTED_SPIDER_EYE: WEAKNESS
GHAST_TEAR: REGENERATION
PHANTOM_MEMBRANE: SLOW_FALLING
BREEZE_ROD: WIND_CHARGED
STONE: INFESTED
COBWEB: WEAVING
SLIME_BLOCK: OOZING
CAKE: SATURATION
GLOWSTONE_DUST: GLOWING
INK_SAC: DARKNESS
CROSSBOW: BAD_OMEN
ROTTEN_FLESH: HUNGER
IRON_PICKAXE: HASTE
GOLDEN_APPLE: ABSORPTION
NETHERITE_BLOCK: RESISTANCE
PRISMARINE_SHARD: MINING_FATIGUE
BROWN_MUSHROOM: NAUSEA
WITHER_ROSE: WITHER
CHORUS_FRUIT: LEVITATION
ENCHANTED_BOOK: LUCK